[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:laravel-serve]
command=sh -c "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:laravel-reverb]
command=php artisan reverb:start --host="0.0.0.0" --port=8080
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
